@W-9625690@: Removed retries of install and smoke test, and temporarily disabled the PagerDuty alerts.

diff --git a/.github/workflows/production-heartbeat.yml b/.github/workflows/production-heartbeat.yml
--- a/.github/workflows/production-heartbeat.yml
+++ b/.github/workflows/production-heartbeat.yml
@@ -22,20 +22,18 @@ jobs:
       # === Make three attempts to install sfdx through npm ===
       - name: Install SFDX
         id: sfdx_install
-        # Sleep for 5 seconds between attempts, since it's possible that problems are network-related.
-        run: npm install -g sfdx-cli || (sleep 5 && npm install -g sfdx-cli) || (sleep 5 && npm install -g sfdx-cli)
+        # If the first attempt fails, wait a minute and try again. After a second failure, wait 5 minutes then try again. Then give up.
+        run: npm install -g sfdx-cli || (sleep 60 && npm install -g sfdx-cli) || (sleep 300 && npm install -g sfdx-cli)
 
-      # === Make three attempts to install the scanner plugin ===
+      # === Attempt to install the scanner plugin ===
       - name: Install Scanner Plugin
         id: scanner_install
-        # Sleep for 5 seconds between attempts, since it's possible that problems are network-related.
-        run: sfdx plugins:install @salesforce/sfdx-scanner || (sleep 5 && sfdx plugins:install @salesforce/sfdx-scanner) || (sleep 5 && sfdx plugins:install @salesforce/sfdx-scanner)
+        run: sfdx plugins:install @salesforce/sfdx-scanner
 
-      # === Make three attempts to execute the smoke tests ===
+      # === Attempt to execute the smoke tests ===
       - name: Run smoke tests
         id: smoke_tests
-        # Sleep for 5 seconds between attempts, since it's possible that problems are network-related.
-        run: smoke-tests/smoke-test${{ matrix.os.exe }} sfdx || (sleep 5 && smoke-tests/smoke-test${{ matrix.os.exe }} sfdx) || (sleep 5 && smoke-tests/smoke-test${{ matrix.os.exe }} sfdx)
+        run: smoke-tests/smoke-test${{ matrix.os.exe }} sfdx
 
       # === Upload the smoke-test-results folder as an artifact ===
       - name: Upload smoke-test-results folder as artifact
@@ -45,26 +43,28 @@ jobs:
           name: smoke-test-results-${{ runner.os }}
           path: smoke-test-results
 
+# This part is commented out for now, so we can run the script for a day or two without risking blowing up PagerDuty.
+# Once we've seen that it works properly, we'll re-enable the alerts.
       # === Report any failures ===
-      - name: Report failures
-        if: ${{ failure() }}
-        shell: bash
-        env:
-          # A link to this run
-          RUN_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        run: |
-          curl --request POST \
-          --data '{"payload": {
-            "summary": "Production heartbeat script failed on ${{ runner.os }}",
-            "source": "Github Actions",
-            "severity": "critical",
-            "custom_details": "SFDX install: ${{ steps.sfdx_install.outcome }}. Scanner install: ${{ steps.scanner_install.outcome }}. Smoke tests: ${{ steps.smoke_tests.outcome }}"
-          },
-          "links": [{
-            "href": "${{ env.RUN_LINK }}",
-            "text": "Link to action execution"
-          }],
-          "event_action": "trigger",
-          "routing_key": "${{ secrets.PAGERDUTY_HEARTBEAT_KEY }}"
-          }' \
-          https://events.pagerduty.com/v2/enqueue
+#      - name: Report failures
+#        if: ${{ failure() }}
+#        shell: bash
+#        env:
+#          # A link to this run
+#          RUN_LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+#        run: |
+#          curl --request POST \
+#          --data '{"payload": {
+#            "summary": "Production heartbeat script failed on ${{ runner.os }}",
+#            "source": "Github Actions",
+#            "severity": "critical",
+#            "custom_details": "SFDX install: ${{ steps.sfdx_install.outcome }}. Scanner install: ${{ steps.scanner_install.outcome }}. Smoke tests: ${{ steps.smoke_tests.outcome }}"
+#          },
+#          "links": [{
+#            "href": "${{ env.RUN_LINK }}",
+#            "text": "Link to action execution"
+#          }],
+#          "event_action": "trigger",
+#          "routing_key": "${{ secrets.PAGERDUTY_HEARTBEAT_KEY }}"
+#          }' \
+#          https://events.pagerduty.com/v2/enqueue
