Experimenting with getting results.

diff --git a/.github/workflows/production-smoke-tests.yml b/.github/workflows/production-smoke-tests.yml
--- a/.github/workflows/production-smoke-tests.yml
+++ b/.github/workflows/production-smoke-tests.yml
@@ -25,7 +25,7 @@ jobs:
         if: ${{ steps.sfdx_first_try.outcome == 'failure' }}
         id: sfdx_second_try
         continue-on-error: true # Retry after second failure
-        run: exit 1
+        run: exit 0
       - name: SFDX install third try
         if: ${{ steps.sfdx_second_try.outcome == 'failure' }}
         id: sfdx_third_try
@@ -40,17 +40,31 @@ jobs:
         if: ${{ steps.scanner_first_try.outcome == 'failure' }}
         id: scanner_second_try
         continue-on-error: true # Retry after second failure
-        run: exit 1
+        run: exit 0
       - name: Scanner install third try
         if: ${{ steps.scanner_second_try.outcome == 'failure' }}
         id: scanner_third_try
         run: exit 0
-      # Report failure'
-      - name: report failures
+
+      # === Make three attempts to execute the smoke tests ===
+      - name: Smoke test first try
+        id: smoke_test_first_try
+        continue-on-error: true # Retry after first failure
+        run: exit 1
+      - name: Smoke test second try
+        if: ${{ steps.smoke_test_first_try.outcome == 'failure' }}
+        id: smoke_test_second_try
+        continue-on-error: true # Retry after second failure
+        run: exit 0
+      - name: Smoke test third try
+        if: ${{ steps.smoke_test_second_try.outcome == 'failure' }}
+        id: smoke_test_third_try
+        run: exit 0
+
+      # === Report any failures ===
+      - name: Report failures
         if: ${{ failure() }}
-        run: |
-          echo 'SFDX install state? ${{ steps.sfdx_third_try.outcome }}'
-          echo 'Scanner install state? ${{ steps.scanner_third_try.outcome }}'
+        run: echo ${{ steps.*.outcome }}
 #
 #
 #
